- name: lsusb
  apt:
    name: "usbutils"
    state: latest
    update_cache: yes
  become: yes
- name: kvaser (download library)
  become: no
  get_url:
    url: "https://www.kvaser.com/download/?utm_source=software&utm_ean=7330130980754&utm_status={{ version }}"
    dest: "{{ role_path }}"

- name: kvaser (unarchive library)
  ansible.builtin.unarchive:
    src: "{{ role_path }}/linuxcan.tar.gz"
    dest: "{{ role_path }}"
    remote_src: yes

- name: kvaser (build the default target)
  make:
    chdir: "{{ role_path }}/linuxcan"

- name: kvaser (Run install target as root)
  make:
    chdir: "{{ role_path }}/linuxcan"
    target: install
  become: yes
